# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [18]:
# importing the NumPy library

import numpy as np

In [19]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = np.arange(0,5)
np_1

# creating an array of zeroes with 5 elements
np_2 = np.zeros(5)
np_2

array([0., 0., 0., 0., 0.])

In [5]:
# checking the created array: np_1
print(np_1)

[0 1 2 3 4]


In [6]:
# checking the created array:np_2
print(np_2)

[0. 0. 0. 0. 0.]


In [9]:
# data type of np_2
type(np_2)
np_2.dtype

dtype('float64')

In [11]:
# specifying the data type of the array in the provided attribute

np.array(np_1,dtype='float')

array([0., 1., 2., 3., 4.])

In [12]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

[0. 1. 2. 3. 4.]


In [14]:
# check the dimension of the arrays
# array np_1
print(np_1.ndim)
print(np_2.ndim)

1
1


In [15]:
# check the dimension of the arrays
# array np_2
np_2.ndim

1

In [23]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(6)

# checking the created array:np_3
print(np_3)

[1. 1. 1. 1. 1. 1.]


In [17]:
# check the dimension of the arrays
# array np_2
np_2.ndim

1

In [18]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [22]:
# creating an array of fixed length
np_4 = np.linspace(0,7)

# checking the created array:np_4
print(np_4)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.         2.14285714 2.28571429 2.42857143
 2.57142857 2.71428571 2.85714286 3.         3.14285714 3.28571429
 3.42857143 3.57142857 3.71428571 3.85714286 4.         4.14285714
 4.28571429 4.42857143 4.57142857 4.71428571 4.85714286 5.
 5.14285714 5.28571429 5.42857143 5.57142857 5.71428571 5.85714286
 6.         6.14285714 6.28571429 6.42857143 6.57142857 6.71428571
 6.85714286 7.        ]


In [23]:
# checking the created array:np_1
np_1

array([0, 1, 2, 3, 4])

In [20]:
# squaring the terms of np_1
np.square(np_1)

array([ 0,  1,  4,  9, 16])

In [25]:
# getting the absolute value of the elements
print(np.absolute(np_1))



[0 1 2 3 4]


In [26]:
np.absolute(np_3)

array([1., 1., 1., 1., 1., 1.])

In [27]:
np.absolute(np_2)

array([0., 0., 0., 0., 0.])

In [28]:
np.sin(np_1)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [29]:
np.cos(np_2)

array([1., 1., 1., 1., 1.])

In [30]:
np.log(np_1)

/home/swathireddy/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

### Empty arrays

In [3]:
# Creating empty arrays
import numpy as np
x = np.arange(1, 6)
y = np.arange(1,6)

# filling the empty array
x.fill(3)
y.fill(4)

In [4]:
# printing the output obtained above
y

array([4, 4, 4, 4, 4])

In [5]:
x

array([3, 3, 3, 3, 3])

### Aggregation of array elements

In [ ]:
# Reducing the elements to a single value based on addition


In [ ]:
# Cummulative addition of elements at each element


In [12]:
np.linalg

<module 'numpy.linalg' from '/home/swathireddy/.local/lib/python3.6/site-packages/numpy/linalg/__init__.py'>

In [13]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [6]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [7]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type here is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [8]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [9]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
# Create a 3 x 4 array of random numbers between 0 and 1
np.random.random([3, 4])

array([[0.42425488, 0.76781255, 0.05896226, 0.08475061],
       [0.28345104, 0.82447817, 0.44044222, 0.38214776],
       [0.67259385, 0.49776927, 0.70831855, 0.40925291]])

In [11]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[0, 1, 8, 7],
       [2, 4, 3, 4],
       [3, 2, 9, 2],
       [9, 8, 1, 2]])